### PR TITLE
some trivial typos/fixes to README.md

### PR DESCRIPTION
**Pull request by fermulator**
* mostly typos fixed
 * some minor punctuation changes

### CODE REVIEW

**Comment by dmk255** [comment]
lgtm

**Comment by fermulator** [comment]
@dmk255  - has been pending for a while, anything missing / TODO before approval?

**Comment by dmk255** [comment]
@fermulator Unfortunately, I don't have write access to merge the repo. My comment was more to add a +1 to the PR for the maintainers.

@benohara Any chance this PR can get approved?

**Comment by benohara** [comment]
Cheers!

**Pull request merged**
